# Generated by Django 5.1.7 on 2025-05-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(upload_to='services/')),
                ('kitchen', models.BooleanField(default=False)),
                ('bathroom', models.BooleanField(default=False)),
                ('bedroom', models.BooleanField(default=False)),
                ('living_room', models.BooleanField(default=False)),
            ],
        ),
    ]
