# Generated by Django 4.2 on 2025-05-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='price',
            new_name='business_price',
        ),
        migrations.AddField(
            model_name='service',
            name='individual_price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=8),
            preserve_default=False,
        ),
    ]
