# Generated by Django 4.2 on 2025-05-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_price_service_business_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='bathroom',
        ),
        migrations.RemoveField(
            model_name='service',
            name='bedroom',
        ),
        migrations.RemoveField(
            model_name='service',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='service',
            name='living_room',
        ),
        migrations.AddField(
            model_name='service',
            name='feature_tags',
            field=models.ManyToManyField(related_name='services', to='services.featuretag'),
        ),
        migrations.AddField(
            model_name='service',
            name='room_tags',
            field=models.ManyToManyField(related_name='services', to='services.roomtag'),
        ),
    ]
