# Generated by Django 4.2 on 2025-05-07 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_featuretag_roomtag_remove_service_bathroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='business_price',
        ),
    ]
