# Generated by Django 5.1.7 on 2025-05-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_extraservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraservice',
            name='service',
        ),
    ]
