# Generated by Django 4.2 on 2025-05-08 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_extraservice_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('extra_service', models.ManyToManyField(related_name='orders', to='services.extraservice')),
                ('service', models.ManyToManyField(related_name='orders', to='services.service')),
            ],
        ),
    ]
