# Generated by Django 4.2 on 2025-05-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='extra_service',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service',
        ),
        migrations.AddField(
            model_name='order',
            name='extra_service',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
