# Generated by Django 4.2 on 2025-05-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_remove_order_extra_service_remove_order_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='extra_service',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service',
        ),
        migrations.AddField(
            model_name='order',
            name='extra_service',
            field=models.ManyToManyField(related_name='orders', to='services.extraservice'),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ManyToManyField(related_name='orders', to='services.service'),
        ),
    ]
